openapi: 3.2.0
info:
  title: Partner Integration settings API
  description: Public API for managing partner integrations
  version: 1.0.0
servers:
- url: https://hq1.appsflyer.com/api/app-integrations/
  description: api server - production
security:
- bearerAuth: []
tags:
- name: Integration settings
paths:
  /copy:
    post:
      deprecated: true
      tags:
      - Integration settings
      summary: Deprecated - Copy partner integration settings
      description: '> ⚠️ Important

        >

        > All API V2 tokens generated before March 10, 2026, 19:00 UTC have been revoked. If your token was generated before this date, please regenerate it. [Learn how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).

        '
      requestBody:
        description: 'Use these examples as a template for your request body:'
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/copyPartnerParams'
            examples:
              Facebook:
                value:
                  pid: facebook_int
                  copy_from_app_id: com.publisher.name
                  copy_to_app_id: com.publisher.name2
                  facebook_app_id: '23502200095693'
                  gp_referrer_decryption_key: 7924423F4528482B4D6251655468576D5A7134743777217A25432A46294A4044
              Snapchat:
                value:
                  pid: snapchat_int
                  copy_from_app_id: com.publisher.name
                  copy_to_app_id: com.publisher.name2
                  snap_app_id: app id
                  mact_tos_accepted: true
              Tiktok:
                value:
                  pid: bytedanceglobal_int
                  copy_from_app_id: com.publisher.name
                  copy_to_app_id: com.publisher.name2
                  tiktok_app_id: app id
        required: true
      responses:
        '200':
          description: 'Partner integration settings copied successfully.


            Response parameters provide a summary of the settings and values copied from the source app to the destination app.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          description: Unauthorized/TOS not accepted
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/AccountTypeError'
                - $ref: '#/components/schemas/UnauthorizedParamError'
                - $ref: '#/components/schemas/UnauthorizedAppError'
                - $ref: '#/components/schemas/TosError'
              examples:
                accountTypeError:
                  value:
                    status: UNAUTHORIZED
                    message: This api is not available for your account type
                appError:
                  value:
                    status: UNAUTHORIZED
                    message: App <app id> is not owned by the user
                paramError:
                  value:
                    status: UNAUTHORIZED
                    message: Your app settings do not allow modifying <param Name> for app <app id>
                tosError:
                  value:
                    status: UNAUTHORIZED
                    message: Attribution terms of service were not accepted for app <app id> and <pid>
        '404':
          description: Integration not found
          content:
            application/json:
              examples:
                integrationNotFound:
                  value:
                    status: NOT_FOUND
                    message: Integration for <pid> was not found. Please check the pid value
        '422':
          description: Missing/invalid input params
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/InvalidValueError'
                - $ref: '#/components/schemas/MissingParamError'
                - $ref: '#/components/schemas/GeneralFailureError'
                - $ref: '#/components/schemas/IntegrationNotEnabledError'
                - $ref: '#/components/schemas/UnmatchedPlatformError'
              examples:
                invalidValueError:
                  value:
                    status: INVALID_VALUE
                    message: <param> value is invalid.
                missingParamError:
                  value:
                    status: MISSING_PARAMETER
                    message: <param> is missing
                generalFailureError:
                  value:
                    status: GENERAL_FAILURE
                    message: At this time the integration can not be activated.Contact your CSM or support@appsflyer.com with a copy of this message
                integrationNotEnabledError:
                  value:
                    status: INACTIVE_INTEGRATION
                    message: Integration for app <app id> with <pid> is not enabled
                unmatchedPlatformError:
                  value:
                    status: PLATFORM_UNMATCHED
                    message: Both apps should be on the same mobile platform
        '500':
          description: Internal server error - please try again
  /v1/copy:
    post:
      tags:
      - Integration settings
      summary: Copy partner integration settings
      description: "> ⚠️ Important\n>\n> All API V2 tokens generated before March 10, 2026, 19:00 UTC have been revoked. If your token was generated before this date, please regenerate it. [Learn how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).\n\nCopy the integration settings from one app to another. Copying the parameters can be done only for apps on the same platform. To retrieve the partner's unique parameters needed for the integration, use the [GET request](https://dev.appsflyer.com/hc/reference/get_v1-partner-params-pid-platform).\n> \U0001F4D8 Note\n> Only parameters of event names with the `af_` prefix can be copied.  \n"
      requestBody:
        description: 'Use these examples as a template for your request body:'
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/copyPartnerParams'
            examples:
              Facebook:
                value:
                  pid: facebook_int
                  copy_from_app_id: com.publisher.name
                  copy_to_app_id: com.publisher.name2
                  general_params:
                    facebook_app_id: '123'
                    gp_referrer_decryption_key: 7924423F4528482B4D6251655468576D5A7134743777217A25432A46294A4044
              Snapchat:
                value:
                  pid: snapchat_int
                  copy_from_app_id: com.publisher.name
                  copy_to_app_id: com.publisher.name2
                  mact_tos_accepted: true
                  general_params:
                    snap_app_id: app id
              Tiktok:
                value:
                  pid: bytedanceglobal_int
                  copy_from_app_id: com.publisher.name
                  copy_to_app_id: com.publisher.name2
                  general_params:
                    tiktok_app_id: app id
        required: true
      responses:
        '200':
          description: 'Partner integration settings copied successfully


            Response parameters provide a summary of the settings and values copied from the source app to the destination app.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        '401':
          description: Unauthorized/TOS not accepted
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/AccountTypeError'
                - $ref: '#/components/schemas/UnauthorizedParamError'
                - $ref: '#/components/schemas/UnauthorizedAppError'
                - $ref: '#/components/schemas/TosError'
              examples:
                accountTypeError:
                  value:
                    status: UNAUTHORIZED
                    message: This api is not available for your account type
                appError:
                  value:
                    status: UNAUTHORIZED
                    message: App <app id> is not owned by the user
                paramError:
                  value:
                    status: UNAUTHORIZED
                    message: Your app settings do not allow modifying <param Name> for app <app id>
                tosError:
                  value:
                    status: UNAUTHORIZED
                    message: Attribution terms of service were not accepted for app <app id> and <pid>
        '404':
          description: Integration not found
          content:
            application/json:
              examples:
                integrationNotFound:
                  value:
                    status: NOT_FOUND
                    message: Integration for <pid> was not found. Please check the pid value
        '422':
          description: Missing/invalid input params
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/InvalidValueError'
                - $ref: '#/components/schemas/MissingParamError'
                - $ref: '#/components/schemas/GeneralFailureError'
                - $ref: '#/components/schemas/IntegrationNotEnabledError'
                - $ref: '#/components/schemas/UnmatchedPlatformError'
              examples:
                invalidValueError:
                  value:
                    status: INVALID_VALUE
                    message: <param> value is invalid.
                missingParamError:
                  value:
                    status: MISSING_PARAMETER
                    message: <param> is missing
                generalFailureError:
                  value:
                    status: GENERAL_FAILURE
                    message: At this time the integration can not be activated.Contact your CSM or support@appsflyer.com with a copy of this message
                integrationNotEnabledError:
                  value:
                    status: INACTIVE_INTEGRATION
                    message: Integration for app <app id> with <pid> is not enabled
                unmatchedPlatformError:
                  value:
                    status: PLATFORM_UNMATCHED
                    message: Both apps should be on the same mobile platform
        '500':
          description: Internal server error - please try again
components:
  schemas:
    UnauthorizedParamError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    IntegrationNotEnabledError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    TosError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    GeneralFailureError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    UnmatchedPlatformError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    AccountTypeError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    copy_from_app_id:
      type: string
      description: 'App to copy integration configuration ***from*** (''source app'')

        Examples per OS:

        - **Android:** com.publisher.name

        - **iOS:** id123456789

        - **Windows Phone:** a1b2c3d4e5f6

        '
    copyPartnerParams:
      title: Set the parameters for the request
      required:
      - pid
      - copy_from_app_id
      - copy_to_app_id
      type: object
      properties:
        pid:
          $ref: '#/components/schemas/pid'
        copy_from_app_id:
          $ref: '#/components/schemas/copy_from_app_id'
        copy_to_app_id:
          $ref: '#/components/schemas/copy_to_app_id'
        general_params:
          type: object
        in_app_postbacks_params:
          type: object
    pid:
      type: string
      description: 'AppsFlyer Partner ID

        '
    InvalidValueError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    MissingParamError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    UnauthorizedAppError:
      properties:
        status:
          type: string
        message:
          type: string
      type: object
    Response:
      properties:
        general_params:
          properties:
            Click Attribution Lookback Window:
              type: string
            Enable Advanced Privacy:
              type: string
            Ignore active users for retargeting:
              type: string
            Install Re-engagement Click Lookback Window:
              type: string
            Re-engagement attribution Enabled:
              type: string
            Re-engagement click-through lookback window:
              type: string
            Re-engagement view-through attribution:
              type: string
            Re-engagement window:
              type: string
            Time window for users to be considered inactive:
              type: string
            View-Through Attribution lookback window:
              type: string
        in_app_postbacks_params:
          properties:
            mapped-in-app-events:
              type: object
      type: object
    copy_to_app_id:
      type: string
      description: 'App to copy integration configuration ***to*** (''destination app'')

        Examples per OS:

        - **Android:** com.publisher.name

        - **iOS:** id123456789

        - **Windows Phone:** a1b2c3d4e5f6

        '
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: '> ⚠️ Important

        >

        > All API V2 tokens generated before March 10, 2026, 19:00 UTC have been revoked. If your token was generated before this date, please regenerate it. [Learn how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).


        HTTP header containing the API token (bearer token) is required. Ask your account admin to [obtain the V2.0 token](https://support.appsflyer.com/hc/en-us/articles/360004562377) from the AppsFlyer dashboard.

        '
