openapi: 3.2.0
info:
  title: Push API Configuration Authentication Token API
  version: 1.0.0
servers:
- url: https://hq1.appsflyer.com/api/pushapi/v1.0/
security:
- Bearer-Authentication: []
tags:
- name: Authentication Token
paths:
  /tokens/app/{app_id}:
    delete:
      tags:
      - Authentication Token
      summary: Delete Push API Authentication Token
      description: '> ⚠️ Important

        >

        > All API V2 tokens generated before March 10, 2026, 19:00 UTC have been revoked. If your token was generated before this date, please regenerate it. [Learn how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).

        '
      parameters:
      - name: app_id
        in: path
        description: Application ID
        example: id121244
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The token has been deleted successfully
          headers:
            deprecated:
              description: is the api version deprecated?
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                    example: 8a3f4fa6-a91c-11ec-b909-0242ac120002
        '401':
          $ref: '#/components/responses/AuthenticationFailed'
        '402':
          description: Push API isn't part of your subscription.
          headers:
            deprecated:
              description: is the api version deprecated
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Missing Asset Push API:
                  value:
                    code: MissingAsset
                    message: Push API isn't part of your subscription. Contact AppsFlyer support or your AppsFlyer account executive
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
        '403':
          description: Account problem occurred
          headers:
            deprecated:
              description: is the api version deprecated
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Account problem:
                  value:
                    code: AccountProblem
                    message: An account problem occurred. Please contact your AppsFlyer account executive.
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
                App ID not found:
                  value:
                    code: UnknownAppid
                    message: The app ID specified wasn't found. Check that the app ID is identical to that in AppsFlyer in your account.
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
        '404':
          $ref: '#/components/responses/VersionDoesntExist'
        '410':
          $ref: '#/components/responses/VersionNoLongerValid'
    put:
      tags:
      - Authentication Token
      summary: Set Push API Authentication Token
      description: '> ⚠️ Important

        >

        > All API V2 tokens generated before March 10, 2026, 19:00 UTC have been revoked. If your token was generated before this date, please regenerate it. [Learn how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).

        '
      parameters:
      - name: app_id
        in: path
        description: Application ID
        example: id121244
        required: true
        schema:
          type: string
      requestBody:
        description: Body for validate URL
        content:
          application/json:
            schema:
              required:
              - token
              type: object
              properties:
                token:
                  type: string
                  maxLength: 2000
                  pattern: "^[ \t\\-_.a-zA-Z0-9]*$"
                  description: "The token value should be a string with a maximum of 2,000 characters, containing only the characters a-z, A-Z, 0-9, and the special characters [ \t-_.]."
                token_name:
                  oneOf:
                  - type: string
                    enum:
                    - Authorization
                  - type: string
                    pattern: ^X-[a-zA-Z0-9\-_]*$
                  maxLength: 30
                  description: The token name must be either 'Authorization' or a string starting with 'X-', consisting of a maximum of 30 characters including only the characters a-z, A-Z, 0-9, '-' and '_'. If the token name is empty or null, it will default to the last received token name, or 'Authorization' if there is none.
      responses:
        '200':
          description: The token has been set successfully
          headers:
            deprecated:
              description: is the api version deprecated?
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                    example: 8a3f4fa6-a91c-11ec-b909-0242ac120002
                  message:
                    type: string
                    example: Your token has been set successfully
        '400':
          description: JSON parsing error
          headers:
            deprecated:
              description: is the api version deprecated
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: JSONParsingError
                message: An error occurred while parsing the JSON body. Check the body and try again..
                requestId: 8a3f4fa6-a91c-11ec-b909-0242ac120002
        '401':
          $ref: '#/components/responses/AuthenticationFailed'
        '402':
          description: Push API isn't part of your subscription.
          headers:
            deprecated:
              description: is the api version deprecated
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Missing Asset Event Type:
                  value:
                    code: MissingAsset
                    message: The specified message type ({event-type} isn't part of your subscription. Contact AppsFlyer support or your AppsFlyer account executive.
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
                Missing Asset Push API:
                  value:
                    code: MissingAsset
                    message: Push API isn't part of your subscription. Contact AppsFlyer support or your AppsFlyer account executive
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
        '403':
          description: Account problem occurred
          headers:
            deprecated:
              description: is the api version deprecated
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Account problem:
                  value:
                    code: AccountProblem
                    message: An account problem occurred. Please contact your AppsFlyer account executive.
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
                App ID not found:
                  value:
                    code: UnknownAppid
                    message: The app ID specified wasn't found. Check that the app ID is identical to that in AppsFlyer in your account.
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
        '404':
          $ref: '#/components/responses/VersionDoesntExist'
        '410':
          $ref: '#/components/responses/VersionNoLongerValid'
        '422':
          description: Schema Error
          headers:
            deprecated:
              description: is the api version deprecated
              schema:
                type: boolean
            deprecationDate:
              description: deprecation date
              schema:
                type: string
            sunsetDate:
              description: sunset date
              schema:
                type: string
            deprecationMessage:
              description: deprecation message
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Invalid JSON format:
                  value:
                    code: SchemaError
                    message: Invalid JSON format or no JSON found. Verify the content and resubmit.
                    request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
components:
  responses:
    VersionNoLongerValid:
      description: The API version listed in the URL is no longer valid
      headers:
        deprecated:
          description: is the api version deprecated
          schema:
            type: boolean
        deprecationDate:
          description: deprecation date
          schema:
            type: string
        sunsetDate:
          description: sunset date
          schema:
            type: string
        deprecationMessage:
          description: deprecation message
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: The API version listed in the URL is no longer valid. Check the API documentation
    AuthenticationFailed:
      description: Authentication failed. The authentication token is not valid.
      headers:
        deprecated:
          description: is the api version deprecated
          schema:
            type: boolean
        deprecationDate:
          description: deprecation date
          schema:
            type: string
        sunsetDate:
          description: sunset date
          schema:
            type: string
        deprecationMessage:
          description: deprecation message
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    VersionDoesntExist:
      description: The API version listed in the URL doesn't exist
      headers:
        deprecated:
          description: is the api version deprecated
          schema:
            type: boolean
        deprecationDate:
          description: deprecation date
          schema:
            type: string
        sunsetDate:
          description: sunset date
          schema:
            type: string
        deprecationMessage:
          description: deprecation message
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: InvalidVersion
            message: The API version listed in the URL doesn't exist. Check the API documentation
            request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
  schemas:
    Error:
      example:
        code: SomeErrorCode
        message: Some error message.
        request_id: 8a3f4fa6-a91c-11ec-b909-0242ac120002
      type: object
      properties:
        status:
          type: integer
        code:
          type: string
        message:
          type: string
        request_id:
          type: string
  securitySchemes:
    Bearer-Authentication:
      type: http
      scheme: bearer
      description: "**Important: API V2 Token Revocation**\n\nAll API V2 tokens generated before March 10, 2026, 19:00 UTC have been revoked. If your token was generated before this date, please regenerate it. [Learn how](https://support.appsflyer.com/hc/en-us/articles/360004562377-Managing-AppsFlyer-tokens).\n\nAuthorization HTTP header containing API V2 token (bearer token) is required.\n\n The admin [gets the V2 token in the dashboard](https://support.appsflyer.com/hc/en-us/articles/360004562377) "
